name: Magento2 Zento Modules CI 
on:
  push:
    branches:
      - dev
  release:
    types: 
      - released
jobs:
  uploadS3:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout-packAzento-test
        uses: actions/checkout@v2
        with:
          repository: zentoshop/infra-packazento
      - name: packAzento-test
        run: |
          ./test
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
     # - name: checkout-packAzento
     #   uses: actions/checkout@v2
     #   with:
     #     repository: zentoshop/infra-packazento
      - name: packAzento
        run: |
          ./packazento
